<?php
define ('_BOARD_PUB','опубликовано');
define ('_BOARD_ADD_CAPTION','Спасибо');
define ('_BOARD_ADD_OSN_INF','Основная информация');
define ('_BOARD_ADD_DOP_INF','Дополнительная информация');
define ('_BOARD_ADD_DOP_INF_TEXT','Укажите дополнительную информацию о Вашей машине в целях экономии времени на ответы по телефону. К примеру: количество владельцев, пробег по РФ, год ввоза авто в РФ, салон, проведенные ремонты, условия эксплуатации и пр.');
define ('_BOARD_ADD_FOTO_INF','Фотографии авто');
define ('_BOARD_DETAIL_COMPL','Характеристика');
define ('_BOARD_ADD_MESS_OK','');
define ('_BOARD_ADD_FOTO_MESS','Фотографии, загруженная в форме первой, будет отображаться на главной странице и первой на странице объявлений<br/>&nbsp;&nbsp;&nbsp;&nbsp;Фотографии принимаются только в формате - jpg');
define ('_BOARD_ADD_FOTO_UPLOADED','Загруженные файлы');
define ('_FIRMS_ADD_FOTO_MESS','Фотографии принимаются только в формате - jpg');
define ('_FIRMS_ADD_FOTO_UPLOADED','Файл загружен');
define ('_BOARD_ADD_CONTACT_INF','Контактная информация');
define ('_BOARD_ADD_USER_NAME','Имя');
define ('_BOARD_ADD_USER_LOGIN','Логин');
define ('_BOARD_ADD_PHONE','Телефон');
define ('_BOARD_ADD_CITY','Город');
define ('_FIRMS_ADD_ANNOT','Аннотация');
define ('_BOARD_ADD_MESS','Пожалуйсто будьте внимательны при заполнении полей. Не забывайте указывать все нули в полях  "Цена", "Мощность", "Пробег", "Объем двигателя"<br/>
В случае предоставления ложной информации об автомобиле (занижение цены, указание неверных технических характеристик) или контактные данные, объявление будет удалено ');
define ('_BOARD_MAIN','Объявление по продаже авто');
define ('_BOARD_MAIN_COUNT_MODEL','Количество моделей');
define ('_BOARD_MAIN_COUNT_BOARD','Количество объявлений');
define ('_FIRMS_ADD_CAPTION','Добавление компании');
define ('_FIRMS_CAPTION','Косметические фирмы и салоны');
define ('_FIRMS_ADD_NAME','Наименование компании');
define ('_FIRMS_ADD_TYPE','Основное направление деятельности компании');
define ('_FIRMS_ADD_OSN_INF','Основная информация');
define ('_FIRMS_ADD_USLUGI_INF','Оказываемые услуги');
define ('_FIRMS_ADD_DOP_INF','Дополнительно');
define ('_FIRMS_ADD_CONTACT_INF','Контактная информация');
define ('_FIRMS_ADD_MESS_OK','Запись добавлена успешно');
define ('_CATEGORY_MAIN_CAPTION',' ');
define ('_CATEGORY_MAIN_MARKS_CAPTION','Марки');
define ('_TYPE_CAPTION','Тип объявления');
define ('_CATEGORY_CAPTION','Категория');
define ('_MARKA_CAPTION','Марка');
define ('_MODEL_CAPTION','Модель');
define ('_TYPE_CUZOV_CAPTION','Тип кузова');
define ('_PRICE_CAPTION','Цена');
define ('_YEAR_VIPUSK_CAPTION','Год выпуска');
define ('_OBEM_CAPTION','Объем двигателя');
define ('_PROBEG_CAPTION','Пробег');
define ('_DOP_INFO','Дополнительно');
define ('_NO_SELECT','- не важно -');
define ('_DATE_CAPTION','Дата');
define ('_YEAR_CAPTION','Год');
define ('_CITY_CAPTION','Город');
define ('_SALE','Продажа');
define ('_FOTO_CAPTION','Фото');
define ('_AUTO_CAPTION','Автомобили');
define ('_ALL_CAPTION','ВСЕ');
define ('_ADDRESS','Адрес');
define ('_ADD_AVTO_IMG','Добавить авто');
define ('_SEARCH_AVTO_IMG','Найти');
define ('_EXTSEARCH_AVTO_IMG','Расширенный поиск');
define ('_ADD_COMPANY_IMG','Добавить компанию');
define ('_AUTOPROIZV','Автопроизводители');
define ('_CONTACTS','Контакты');
define ('_INFORMERS','Информеры');
define ('_PARTNERS','Партнеры');
define ('_EMAIL','e-mail');
define ('_BOARD_USER_NAME','Имя');
define ('_NO_BOARDS','<br />В этом разделе траснспортные средства не найдены. <br /><br />На сайте можно бесплатно размещать автомобили, мотоциклы, спецтехнику. Для этого Вам потребуется не более 2-х минут. <br /><br /><a href="/dobavit-avtomobil.html">Перейти к добавлению</a> <br /><br />  ');
define ('_NO_BOARDS_MARKA1','<br />Траснспортные средства марки ');
define ('_NO_BOARDS_MARKA2',' не найдены. <br /><br />На сайте можно бесплатно размещать автомобили, мотоциклы, спецтехнику. Для этого Вам потребуется не более 2-х минут. <br /><br /><a href="/dobavit-avtomobil.html">Перейти к добавлению</a> <br /><br />  ');
define ('_BOARD_ADD_USER_PASSWD','Пароль');
define ('_BOARD_USERS_EXIST','Пользователь с таким именем уже сществует');
define ('_BOARD_EMAIL_EXIST','Пользователь с таким e-mail уже сществует');
define ('_BOARD_NO_FOTO','Нельзя добавлять объявления без фотографии');
define ('_BOARD_USER_PHONE','Телефон рабочий');
define ('_BOARD_USER_PHONE_HOME','Телефон домашний');
define ('_BOARD_USER_MOBILE','Мобильный');
define ('_BOARD_USER_EMAIL','e-mail');
define ('_BOARD_ADD_PASSWD_REPEAT','Подтвердите пароль');
define ('_BOARD_ADD_CAPTCHA','Введите текст с картинки:');
define ('_BOARD_WRONG_CPATCHA','Введенный текст не совпадает с картинкой:');
define ('_BOARD_EXTSEARCH_CAPTION','Расширенный поиск');
define ('_BOARD_NO_VALID','Введенные данные содержат ошибку.');
?>